plugins {
    id 'com.android.application'
}

android {
    namespace 'com.maplatform.app'
    compileSdk 34

    defaultConfig {
        applicationId "com.maplatform.app"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    signingConfigs {
        release {
            storeFile file("ma-platform-key.jks")
            storePassword "M.A@2026#Key"
            keyAlias "ma-platform-key"
            keyPassword "M.A@2026#Key"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'),
                    'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    lint {
        abortOnError false
        checkReleaseBuilds false
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
